require("config_packer")
require("config_settings")
require("config_mappings")
require("config_self")
require("config_lsp")

require("mason").setup()
require('ufo').setup()
require("oil").setup()
require('Comment').setup()
